# Generated by Django 4.2.5 on 2023-11-30 18:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        )
    ]
