# Generated by Django 4.2.5 on 2023-11-30 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0002_product_offer_price')]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='size_chart',
            field=models.ImageField(blank=True, null=True, upload_to='web/size_charts'),
        )
    ]
