# Generated by Django 4.2.5 on 2023-11-30 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0003_subcategory_size_chart')]

    operations = [
        migrations.AlterField(
            model_name='availablesize',
            name='bottom_size',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Bottom Hem'),
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='inseem_length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Inseam Length'),
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Outseam Length'),
        ),
        migrations.AlterField(
            model_name='availablesize',
            name='thighs',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Thighs'),
        ),
    ]
