# Generated by Django 4.2.5 on 2023-11-30 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('web', '0004_alter_availablesize_bottom_size_and_more')]

    operations = [
        migrations.RemoveField(model_name='product', name='subtitle'),
        migrations.AddField(
            model_name='availablesize',
            name='is_stockout',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=False),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product_option',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='web.availablesize', verbose_name='Select Size:'
            ),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_status',
            field=models.CharField(
                choices=[('Available', 'Available'), ('LaunchingSoon', 'Launching Soon')],
                default='Available',
                max_length=100,
            ),
        ),
    ]
