# Generated by Django 4.2.5 on 2023-12-01 09:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('web', '0005_remove_product_subtitle_availablesize_is_stockout_and_more')]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        )
    ]
